/// Flutter icons Customicons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Customicons
///      fonts:
///       - asset: fonts/Customicons.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class Customicons {
  Customicons._();

  static const _kFontFam = 'Customicons';
  static const IconData account_selected = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData account_unselected = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData avatar = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData details_selected = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData details_unselected = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData notebook = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData subscribe = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData support = const IconData(0xe808, fontFamily: _kFontFam);
}
